# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Videos', url: 'facts'}
- {name: 'Shows', url: 'resources'}
- {name: 'Podcasts', url: 'sample-posts'}
- {name: 'Watchcast', url: 'documentation'}
- {name: 'Ramblecast', url: 'contact'}
- {name: 'About', url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/nextlander', alt: ''}
- {icon: 'youtube', link: 'https://youtube.com/channel/UCO0gHyqLNeIrCAjwlO2BmiA', alt: '-brand'}
- {icon: 'twitch', link: 'https://twitch.tv/nextlander', alt: ''}
- {icon: 'podcast', link: 'https://podcasts.apple.com/us/podcast/the-nextlander-podcast/id1570737028', alt: '-solid'}
#- {icon: 'envelope', link: 'podcast@nextlander.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
